# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'editathon'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',  url: 'about'}
- {name: 'Get ready',       url: 'pre-event'}
- {name: 'Event mechanism', url: 'during-event'}
- {name: 'Learning resources', url: 'resources'}
- {name: 'Docs',      url: 'documentation'}
- {name: 'Contact & Acks', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link:    'https://twitter.com/'}
- {icon: 'instagram', link:  'https://instagram.com/'}
- {icon: 'envelope', link:   'mailto:editathon.nutrition@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
